/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const IFabricaiBankAccount = t.iface([], {
  "iban": "string",
  "bic": "string",
});

const exportedTypeSuite: t.ITypeSuite = {
  IFabricaiBankAccount,
};
export default exportedTypeSuite;
