/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const IFabricaiDimensionItemValue = t.iface([], {
  "dimensionId": "string",
  "itemId": "string",
  "value": "number",
});

const exportedTypeSuite: t.ITypeSuite = {
  IFabricaiDimensionItemValue,
};
export default exportedTypeSuite;
