/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const TVatStatusStringFinland = t.union(t.lit('vat_1'), t.lit('vat_10'), t.lit('vat_12'), t.lit('vat_16'), t.lit('vat_7'), t.lit('vat_8'), t.lit('vat_9'), t.lit('vat_3'), t.lit('vat_36'), t.lit('vat_14'), t.lit('vat_15'), t.lit('vat_37'), t.lit('vat_17'), t.lit('vat_18'), t.lit('vat_19'), t.lit('vat_20'), t.lit('vat_21'), t.lit('vat_23'), t.lit('vat_24'), t.lit('vat_25'), t.lit('vat_26'), t.lit('vat_27'), t.lit('vat_28'), t.lit('vat_29'), t.lit('vat_30'), t.lit('vat_31'), t.lit('vat_32'), t.lit('vat_38'), t.lit('vat_39'), t.lit('vat_4'), t.lit('vat_40'), t.lit('vat_41'), t.lit('vat_42'), t.lit('vat_43'), t.lit('vat_44'), t.lit('vat_45'), t.lit('vat_6'), t.lit('vat_100'), t.lit('vat_101'), t.lit('vat_102'), t.lit('vat_103'));

export const IFabricaiDimensionItemValue = t.iface([], {
  "dimensionId": "string",
  "itemId": "string",
  "value": "number",
});

export const IFabricaiInvoiceRow = t.iface([], {
  "id": "string",
  "productCode": "string",
  "product": "string",
  "comment": "string",
  "unit": "string",
  "quantity": "number",
  "unitPriceInOriginalCurrency": "number",
  "valueInOriginalCurrency": "number",
  "value": "number",
  "vatPercent": "number",
  "account": "string",
  "vatStatus": "TVatStatusStringFinland",
  "dimensionItemValues": t.array("IFabricaiDimensionItemValue"),
});

const exportedTypeSuite: t.ITypeSuite = {
  TVatStatusStringFinland,
  IFabricaiDimensionItemValue,
  IFabricaiInvoiceRow,
};
export default exportedTypeSuite;
