/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const EFabricaiEndpointResponseStatus = t.enumtype({
  "OK": "OK",
  "FAIL": "FAIL",
});

export const IFabricaiEndpointResponseWrapper = t.iface([], {
  "status": "EFabricaiEndpointResponseStatus",
  "retryable": "boolean",
  "retryDelayMs": "number",
  "message": t.opt("string"),
  "data": t.opt("any"),
});

export const IFabricaiEndpointResponseJWT = t.iface(["IFabricaiEndpointResponseWrapper"], {
  "data": t.opt(t.iface([], {
    "code": t.opt("string"),
    "organization": t.opt("any"),
  })),
});

const exportedTypeSuite: t.ITypeSuite = {
  EFabricaiEndpointResponseStatus,
  IFabricaiEndpointResponseWrapper,
  IFabricaiEndpointResponseJWT,
};
export default exportedTypeSuite;
