/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const IFabricaiAccount = t.iface([], {
  "name": "string",
  "ledgerAccountCode": "string",
});

export const IFabricaiCOA = t.iface([], {
  "ledgerAccountCodes": t.array("IFabricaiAccount"),
});

const exportedTypeSuite: t.ITypeSuite = {
  IFabricaiAccount,
  IFabricaiCOA,
};
export default exportedTypeSuite;
