/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const IFabricaiDimensionItem = t.iface([], {
  "itemId": "string",
  "codeName": "string",
});

export const IFabricaiDimension = t.iface([], {
  "id": "string",
  "name": "string",
  "items": t.array("IFabricaiDimensionItem"),
});

export const IFabricaiDimensions = t.iface([], {
  "dimensions": t.array("IFabricaiDimension"),
});

const exportedTypeSuite: t.ITypeSuite = {
  IFabricaiDimensionItem,
  IFabricaiDimension,
  IFabricaiDimensions,
};
export default exportedTypeSuite;
