/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const IFabricaiFiscalYear = t.iface([], {
  "fiscalPerdiodTreshold": "number",
});

const exportedTypeSuite: t.ITypeSuite = {
  IFabricaiFiscalYear,
};
export default exportedTypeSuite;
